
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Backend Test Suite
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: weather_user
          POSTGRES_PASSWORD: strongpassword
          POSTGRES_DB: weatherdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U weather_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: postgresql://weather_user:strongpassword@localhost:5432/weatherdb
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Generate Prisma client & deploy migrations
        run: |
          npx prisma generate
          npx prisma migrate deploy
        working-directory: ./backend

      - name: Sync schema to DB
        run: npx prisma db push --accept-data-loss
        working-directory: ./backend

      - name: Seed database
        run: node scripts/seedCities.js
        working-directory: ./backend

      - name: Run tests
        run: npm test
        working-directory: ./backend
